### ISSUE TITLE
Example for foreign key

### ISSUE THREAD

**Issue by Clement-Jean** [chippyash/db-plantuml#2]
I was checking your examples and couldn't figure out how to use foreign keys. The documentation says that foreign key are automatically created but I'm not sure how. Here is my use case:

```
Table(course, name="Course") {
	primary()
	unique(name, string(l=30))
	description :text()
}

Table(price, name="Price") {
	primary()
	amount :decimal
	currency :string(l=3)
}

Table(course_price, name="CoursePrice") {
        'replace these with foreign_key
	**FK course_id** :unsigned int 
	**FK price_id** :unsigned int
}
```

**Comment by akzincsystems** [comment]
Foreign keys are generated by the addition of relationships between tables. Check out the example puml files that were used to create the images in the readme.
